# Interactive script to create .env.docker file
# Configures PostgreSQL (primary database for the agent pipeline)

Write-Host "PostgreSQL Docker Environment Setup" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

# Prompt for PostgreSQL User
$defaultPgUser = "postgres"
Write-Host "Enter PostgreSQL user [$defaultPgUser]: " -NoNewline -ForegroundColor Yellow
$pgUser = Read-Host
if ([string]::IsNullOrWhiteSpace($pgUser)) {
    $pgUser = $defaultPgUser
}
Write-Host "Using PostgreSQL user: $pgUser" -ForegroundColor Green

# Prompt for PostgreSQL Password
$pgPassword = Read-Host "Enter PostgreSQL password (required)"
while ([string]::IsNullOrWhiteSpace($pgPassword)) {
    Write-Host "Password cannot be empty." -ForegroundColor Red
    $pgPassword = Read-Host "Enter PostgreSQL password (required)"
}
Write-Host "PostgreSQL password set." -ForegroundColor Green

# Prompt for PostgreSQL Database
$defaultPgDb = "talent_finder"
Write-Host "Enter PostgreSQL database name [$defaultPgDb]: " -NoNewline -ForegroundColor Yellow
$pgDb = Read-Host
if ([string]::IsNullOrWhiteSpace($pgDb)) {
    $pgDb = $defaultPgDb
}
Write-Host "Using database name: $pgDb" -ForegroundColor Green

# Prompt for PostgreSQL Port
$defaultPgPort = "5432"
Write-Host "Enter PostgreSQL port [$defaultPgPort]: " -NoNewline -ForegroundColor Yellow
$pgPort = Read-Host
if ([string]::IsNullOrWhiteSpace($pgPort)) {
    $pgPort = $defaultPgPort
} else {
    $pgPortNum = 0
    if (-not [int]::TryParse($pgPort, [ref]$pgPortNum) -or $pgPortNum -lt 1 -or $pgPortNum -gt 65535) {
        Write-Host "Invalid port number. Using default: $defaultPgPort" -ForegroundColor Yellow
        $pgPort = $defaultPgPort
    }
}
Write-Host "Using port: $pgPort" -ForegroundColor Green

# Create .env.docker file
$envContent = @"
# PostgreSQL Docker Configuration (primary database — agent pipeline)
# Generated by setup-env-docker.ps1

# PostgreSQL user
POSTGRES_USER=$pgUser

# PostgreSQL password
POSTGRES_PASSWORD=$pgPassword

# PostgreSQL database name
POSTGRES_DB=$pgDb

# Port mapping for PostgreSQL
POSTGRES_PORT=$pgPort
"@

$envFilePath = Join-Path (Join-Path $PSScriptRoot "..") ".env.docker" | Resolve-Path -ErrorAction SilentlyContinue
if (-not $envFilePath) {
    $envFilePath = Join-Path (Get-Location) ".env.docker"
}

$envContent | Out-File -FilePath $envFilePath -Encoding utf8 -NoNewline

Write-Host ""
Write-Host "Successfully created .env.docker file at: $envFilePath" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Start PostgreSQL: docker compose --env-file .env.docker up postgres -d" -ForegroundColor Yellow
Write-Host "2. Seed PostgreSQL:  python scripts/pg-seed-data/seed_pg_database.py" -ForegroundColor Yellow
